apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: nexus
  name: docker
spec:
  host: docker.apps.adriaanmolendijk.info
  port:
    targetPort: 8082
  to:
    kind: ""
    name: nexus
  tls:
    insecureEdgeTerminationPolicy: None
    termination: edge
