apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: nexus
  name: nexus
spec:
  host: nexus.apps.adriaanmolendijk.info
  port:
    targetPort: 8081
  to:
    kind: ""
    name: nexus
  tls:
    insecureEdgeTerminationPolicy: None
    termination: edge
