apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
    name: default:spring-{{ .Values.serviceAccountName }}-role
    namespace: {{ .Release.Namespace }}
roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: Role
    name: spring-{{ .Values.serviceAccountName }}-role
subjects:
    - kind: ServiceAccount
      name: default
      namespace: {{ .Release.Namespace }}
