kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: spring-{{ .Values.serviceAccountName }}-role
rules:
  - apiGroups: ["", "extensions", "apps"]
    resources: ["configmaps", "pods", "services", "endpoints", "secrets"]
    verbs: ["get", "list", "watch"]

