apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.web.name }}
  annotations:
    boot.spring.io/actuator: http://:8080/actuator
  labels:
    app: {{ .Values.web.name }}
    chart: {{ template "api-gateway.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: {{ .Values.web.name }}
    release: {{ .Release.Name }}
---
