replicaCount: 1

web:
  name: frontend-app
  image:
    repository: docker.apps.openshift-1.blierop.com/frontend-app
    tag: latest
    pullPolicy: IfNotPresent
service:
  type: ClusterIP
  port: 8080

