replicaCount: 1

web:
  name: api-gateway
  image:
    repository: docker.apps.blierop.com/api-gateway
    tag: latest
    pullPolicy: IfNotPresent
  enviroment: prod
  ingress:
    issuer: letsencrypt-prod
    domain: example.apps.blierop.com
    secretName: cg-demo-com-tls
    path: /
    serviceMesh:
      enabled: true
service:
  type: ClusterIP
  port: 8080
serviceAccountName: example-app

secrets: {}

